### ISSUE TITLE
Godoc comments on exported types and methods

### ISSUE THREAD

**Issue by ZenGround0** [libp2p/go-libp2p-routing#41]
Came to this package to understand the notification system and found exported types and functions without godoc comments to help with this.  nbd but a nice thing to have for the future.

Checking out the [CI script](https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh) it looks like there is not linting going on as part of the build process.  I'm sure this is tracked or was decided differently somewhere else, but flagging that running a linter on CI across libp2p repos would help with the general case.

**Comment by Kubuxu** [comment]
In go-ipfs we use Codeclimate for this. It prevents us from introducing things like that for new code and encourages fixing it for the old.

**Comment by marten-seemann** [comment]
In quic-go I recently switched from gometalinter to [golangci-lint](https://github.com/golangci/golangci-lint/). It's pretty fast and easy to configure.

**Comment by Stebalien** [comment]
Fix in https://github.com/libp2p/go-libp2p-core/pull/88.
